// <auto-generated />
using System;
using GMAO.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GMAO.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GmaoDbContext))]
    [Migration("20260723153114_UpdateSeedCicam")]
    partial class UpdateSeedCicam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GMAO.Domain.Entities.Campagne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Etat")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Campagnes", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Competences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Maintenance mécanique et électrique combinée",
                            Nom = "Électromécanicien"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Réseaux électriques, câblage et moteurs",
                            Nom = "Électricien industriel"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Programmation API Siemens, Schneider, automates et capteurs",
                            Nom = "Automaticien"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Soudure tuyauterie inox et structures métalliques",
                            Nom = "Soudeur"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Maintenance mécanique lourde, réducteurs, convoyeurs",
                            Nom = "Mécanicien"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.DemandeIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentaireRejet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePanne")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DemandeurId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("EquipementId");

                    b.ToTable("DemandesIntervention", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chemin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EquipementId")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("OTId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanPreventifId")
                        .HasColumnType("integer");

                    b.Property<long>("TailleFichierOctets")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("OTId");

                    b.HasIndex("PlanPreventifId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Criticite")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateAchat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinGarantie")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateMiseEnService")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Etat")
                        .HasColumnType("integer");

                    b.Property<int>("FamilleId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int>("LocalisationId")
                        .HasColumnType("integer");

                    b.Property<string>("Marque")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modele")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FamilleId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Equipements", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Famille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("IconeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Familles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pompes hydrauliques et centrifuges",
                            Nom = "Pompes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chaudières et générateurs de vapeur",
                            Nom = "Chaudières"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Convoyeurs et tapis transporteurs",
                            Nom = "Convoyeurs"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Compresseurs d'air et de gaz",
                            Nom = "Compresseurs"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Moteurs électriques AC/DC",
                            Nom = "Moteurs Electriques"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Groupes frigorifiques et chambres froides",
                            Nom = "Réfrigération"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Autoclaves et tunnels de stérilisation",
                            Nom = "Stérilisateurs"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Machines de remplissage et dosage",
                            Nom = "Remplisseuses"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.FamillePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("FamillesPieces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Roulements & Paliers"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Joints & Garnitures"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Courroies & Chaînes"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Filtres"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Lubrifiants & Huiles"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Composants Electriques"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Visserie & Boulonnerie"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Contact")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Fournisseurs", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdresseIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AnciennesValeurs")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NouvellesValeurs")
                        .HasColumnType("text");

                    b.Property<string>("TableConcernee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Historiques", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CausePanne")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OTId")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Solution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TempsPasse")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OTId")
                        .IsUnique();

                    b.ToTable("Interventions", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Localisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Localisations", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OTId")
                        .HasColumnType("integer");

                    b.Property<int>("PieceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OTId");

                    b.HasIndex("PieceId");

                    b.HasIndex("UserId");

                    b.ToTable("MouvementsStock", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LienUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LuAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.OrdresTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampagneId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CoutMainOeuvre")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CoutPieces")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CoutSousTraitance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebutPrevue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebutReelle")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinPrevue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinReelle")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DemandeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NumeroOT")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnicienId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeMaintenance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.HasIndex("DemandeId")
                        .IsUnique();

                    b.HasIndex("EquipementId");

                    b.HasIndex("NumeroOT")
                        .IsUnique();

                    b.HasIndex("ResponsableId");

                    b.HasIndex("TechnicienId");

                    b.ToTable("OrdresTravail", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Emplacement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FamillePieceId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("StockActuel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("StockMaximum")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("StockMinimum")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Unite")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamillePieceId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Pieces", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.PlanPreventif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EquipementId")
                        .HasColumnType("integer");

                    b.Property<int>("Frequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProchaineDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TypeDeclenchement")
                        .HasColumnType("integer");

                    b.Property<string>("UniteMesure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("PlansPreventifs", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrateur d'une société avec accès complet sur son périmètre",
                            Nom = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gestion des OT, validation des demandes et rapports",
                            Nom = "Responsable Maintenance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Supervision des techniciens et suivi des OT",
                            Nom = "Chef Equipe"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Exécution des interventions",
                            Nom = "Technicien"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Déclaration des pannes",
                            Nom = "Production"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gestion du stock de pièces de rechange",
                            Nom = "Magasinier"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Administrateur plateforme - gère toutes les sociétés",
                            Nom = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CodeTenant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailContact")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodeTenant")
                        .IsUnique();

                    b.ToTable("Societes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeTenant = "tenant-midi",
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmailContact = "cicam@midi.com",
                            IsActive = true,
                            Nom = "cicam"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.TachePreventive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DureeEstimeeMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("EstObligatoire")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("TachesPreventives", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.TechnicienCompetence", b =>
                {
                    b.Property<int>("TechnicienId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("integer");

                    b.HasKey("TechnicienId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("TechnicienCompetences", (string)null);
                });

            modelBuilder.Entity("GMAO.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@gmao.com",
                            IsActive = true,
                            Nom = "Super",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Prenom = "Admin",
                            RoleId = 7,
                            Telephone = "+21699999999"
                        });
                });

            modelBuilder.Entity("GMAO.Domain.Entities.DemandeIntervention", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.User", "Demandeur")
                        .WithMany("DemandesIntervention")
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Equipement", "Equipement")
                        .WithMany("DemandesIntervention")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Demandeur");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Document", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Equipement", "Equipement")
                        .WithMany("Documents")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.OrdresTravail", "OT")
                        .WithMany("Documents")
                        .HasForeignKey("OTId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.PlanPreventif", "PlanPreventif")
                        .WithMany("Documents")
                        .HasForeignKey("PlanPreventifId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("OT");

                    b.Navigation("PlanPreventif");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Equipement", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Famille", "Famille")
                        .WithMany("Equipements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Fournisseur", "Fournisseur")
                        .WithMany("Equipements")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Localisation", "Localisation")
                        .WithMany("Equipements")
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Famille");

                    b.Navigation("Fournisseur");

                    b.Navigation("Localisation");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Historique", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.User", "User")
                        .WithMany("Historiques")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.OrdresTravail", "OT")
                        .WithOne("Intervention")
                        .HasForeignKey("GMAO.Domain.Entities.Intervention", "OTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OT");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Localisation", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Localisation", "Parent")
                        .WithMany("SousLocalisations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.OrdresTravail", "OT")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("OTId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Piece", "Piece")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OT");

                    b.Navigation("Piece");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Notification", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.OrdresTravail", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Campagne", "Campagne")
                        .WithMany("OrdresTravail")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.DemandeIntervention", "Demande")
                        .WithOne("OrdreTravail")
                        .HasForeignKey("GMAO.Domain.Entities.OrdresTravail", "DemandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Equipement", "Equipement")
                        .WithMany("OrdresTravail")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.User", "Responsable")
                        .WithMany("OrdresTravailResponsable")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.User", "Technicien")
                        .WithMany("OrdresTravailTechnicien")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campagne");

                    b.Navigation("Demande");

                    b.Navigation("Equipement");

                    b.Navigation("Responsable");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Piece", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.FamillePiece", "FamillePiece")
                        .WithMany("Pieces")
                        .HasForeignKey("FamillePieceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Fournisseur", "Fournisseur")
                        .WithMany("Pieces")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FamillePiece");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.PlanPreventif", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Equipement", "Equipement")
                        .WithMany("PlansPreventifs")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.TachePreventive", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.PlanPreventif", "Plan")
                        .WithMany("Taches")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.TechnicienCompetence", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Competence", "Competence")
                        .WithMany("TechnicienCompetences")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.User", "Technicien")
                        .WithMany("TechnicienCompetences")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.User", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Societe", "Societe")
                        .WithMany("Users")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Campagne", b =>
                {
                    b.Navigation("OrdresTravail");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Competence", b =>
                {
                    b.Navigation("TechnicienCompetences");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.DemandeIntervention", b =>
                {
                    b.Navigation("OrdreTravail");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Equipement", b =>
                {
                    b.Navigation("DemandesIntervention");

                    b.Navigation("Documents");

                    b.Navigation("OrdresTravail");

                    b.Navigation("PlansPreventifs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.FamillePiece", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Fournisseur", b =>
                {
                    b.Navigation("Equipements");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Localisation", b =>
                {
                    b.Navigation("Equipements");

                    b.Navigation("SousLocalisations");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.OrdresTravail", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Intervention");

                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Piece", b =>
                {
                    b.Navigation("MouvementsStock");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.PlanPreventif", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Taches");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Societe", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.User", b =>
                {
                    b.Navigation("DemandesIntervention");

                    b.Navigation("Historiques");

                    b.Navigation("Notifications");

                    b.Navigation("OrdresTravailResponsable");

                    b.Navigation("OrdresTravailTechnicien");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TechnicienCompetences");
                });
#pragma warning restore 612, 618
        }
    }
}
